
CREATE TABLE IF NOT EXISTS aditions (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    numberOne integer NOT NULL,
    numberTwo integer NOT NULL,
    result integer NOT NULL
);

-- list al tables
\dt

